name: Run Tests
on:
  workflow_call:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.15.1
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests for @repo/base
        run: pnpm run --filter @repo/base test

      - name: Run tests for @repo/ioloc
        run: pnpm run --filter @repo/ioloc test

      - name: Run tests for @repo/translate
        run: pnpm run --filter @repo/translate test
